### ISSUE TITLE
Don't depend on spree

### ISSUE THREAD

**Issue by dandyhat** [jumph4x/spree-google-base#1]
Don't think you should have spree in the gemfile. Can't install on newer versions.

**Comment by jumph4x** [comment]
Spree is in the gemspec. And the extension is unusable outside of the context of a Spree application.

Explain your rationale further, give steps to reproduce and all.

**Comment by dandyhat** [comment]
Many spree gems don't reference spree in the gemfile.

Right now you can't install this gem on 1.1 because of the reference.

**Comment by jumph4x** [comment]
Firstly, correct me if I am wrong but Gemfiles have no effect in the context of you using this in your project. Only .gemspec does. 

Secondly, wouldn't this instead warrant a branch in the repository rather than removing dependency?

**Comment by dandyhat** [comment]
I'm no expert. It just failed installing on 1.1 for me. Rather new to ruby and gems.

**Comment by jumph4x** [comment]
Give me the trace and stuffs.

**Comment by mcasimir** [comment]
Is this the same issue?

Bundler could not find compatible versions for gem "spree":
  In Gemfile:
    spree_google_base (>= 0) ruby depends on
      spree (~> 1.0.0) ruby

```
spree (1.1.0)
```

**Comment by jumph4x** [comment]
Correct. 

@mcasimir @dandyhat I loosened up the deps for you guys: https://github.com/jumph4x/spree-google-base/commit/f7917f375a9e8cb69f9daa8cca7a73d67a127d3d
