### ISSUE TITLE
Support for Spree 1.3 & Other Improvements

### ISSUE THREAD

**Issue by treyperkins** [jumph4x/spree-google-base#10]
I've update my fork a bit to work with spree 1.3 and was wondering if you wanted pull from it directly, or create a new branch to pull into?

I've also added support for the google product categories (ex: Apparel > Jewelry > Necklaces), the feed no longer pulls deleted products in 1.3, and I added a test mode that appends _test to the xml filename uploaded to google for debugging purposes.

I'm in process of adding support for full google product attributes using the Spree product properties system.

Sorry for spamming an issue with this, but wasn't sure where else would be appropriate.

**Comment by jumph4x** [comment]
Totally down to pull this in, except let's do it atomically, if possible. 

For starters, does the 1.3 branch break 1.2 compatibility? If not, we'll pull straight to master.

**Comment by treyperkins** [comment]
I don't have a copy of 1.2 I can currently test on, but I'll try to get one setup tonight so I can answer that.

Really, I think all I had to do for 1.3 was add new deface overrides to injects the links in the control panel in 1.3.

**Comment by jumph4x** [comment]
Roger. Standing by.
