### ISSUE TITLE
NoMethodError in Spree/admin/google_base_settings#show

### ISSUE THREAD

**Issue by samhamilton** [jumph4x/spree-google-base#2]
When trying to go to http://localhost:3000/admin/google_base_settings I get the following error:

Rendered /Users/samhamilton/.rvm/gems/ruby-1.9.3-p125/bundler/gems/spree-google-base-0047fb622b2b/app/views/spree/admin/google_base_settings/show.html.erb within spree/layouts/admin (6.0ms)
Completed 500 Internal Server Error in 431ms

ActionView::Template::Error (title preference not defined):
    4: 
    5: <table>
    6:   <% [:title, :public_domain, :description, :ftp_username].each do |setting| %>
    7:     <%= setting_presentation_row(setting) %>
    8:   <% end %>
    9:   <%= setting_presentation_row(:ftp_password, true) %>
    10:   <%= setting_presentation_row(:enable_taxon_mapping) %>

Rendered /Users/samhamilton/.rvm/gems/ruby-1.9.3-p125/gems/actionpack-3.1.4/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.3ms)

I am using Spree 1.0.4 & the lastest spree-google-base code from github. 

Thanks

**Comment by jumph4x** [comment]
Ahh yes. Thank you. Will address.

**Comment by samhamilton** [comment]
Brilliant! Many Thanks!

**Comment by jumph4x** [comment]
Haven't forgotten about it. Bootstrapping a test app right now.

**Comment by jumph4x** [comment]
Having a ridiculously difficult time testing views. This is unnecessarily painful. 

Use a migration to set your options meanwhile, bringing some of this up to the Spree core.

**Comment by ehoch** [comment]
Any update on this?  Or sample migration to use for now?

**Comment by jumph4x** [comment]
Will have time to fix at the beginning of next week. I had submitted a path
to alter the behavior of admin head to Spree core andbit got pulled.

Ill revisit early next week.
On May 23, 2012 4:49 PM, "Eric Hochberger" <
reply@reply.github.com>
wrote:

**Comment by romul** [comment]
Fixed as part of https://github.com/jumph4x/spree-google-base/commit/0d649f42a0a7078c91b692e81f00cf8627e577f2
