### ISSUE TITLE
Trying to implement on Spree 1.1.X

### ISSUE THREAD

**Issue by w0lver** [jumph4x/spree-google-base#4]
First the readme is out of date the task to run is now: rake spree_google_base:generate_and_transfer

Also I am getting the following when I try to run the task:
Rosss-MacBook-Pro:tatp_store RossRankin$ rake --trace spree_google_base:generate_and_transfer
*\* Invoke spree_google_base:generate_and_transfer (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute spree_google_base:generate_and_transfer
rake aborted!
uninitialized constant Spree::Store
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/bundler/gems/spree-google-base-0d649f42a0a7/lib/spree_google_base/feed_builder.rb:10:in `generate_and_transfer'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/bundler/gems/spree-google-base-0d649f42a0a7/lib/tasks/spree_google_base_extension_tasks.rake:5:in`block (2 levels) in <top (required)>'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`block in execute'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`execute'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:144:in`invoke'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block (2 levels) in top_level'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`block in top_level'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:88:in`top_level'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/bin/rake:33:in`<top (required)>'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/bin/rake:19:in `load'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/bin/rake:19:in`<main>'
Tasks: TOP => spree_google_base:generate_and_transfer

**Comment by jumph4x** [comment]
This will be fixed soon. We've begun work on updating to 1-1-stable.

Stay tuned.

**Comment by w0lver** [comment]
Looks like Ryan fixed that issue above... the next issue is:
*\* Invoke spree_google_base:generate_and_transfer (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute spree_google_base:generate_and_transfer
rake aborted!
undefined method `each' for #<SpreeGoogleBase::FeedBuilder:0x007fe0c45f8460>
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/bundler/gems/spree-google-base-9f4ca6741c79/lib/spree_google_base/feed_builder.rb:18:in`generate_and_transfer'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/bundler/gems/spree-google-base-9f4ca6741c79/lib/tasks/spree_google_base_extension_tasks.rake:5:in `block (2 levels) in <top (required)>'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/bin/rake:19:in`load'
/Volumes/MacintoshHD/Users/RossRankin/.rvm/gems/ruby-1.9.2-p318@tatp_store/bin/rake:19:in `<main>'
Tasks: TOP => spree_google_base:generate_and_transfer

BTW, if this inn't helpful, let me know and I'll stop updating...

**Comment by jumph4x** [comment]
@w0lver I can do all of this on my end, thanks :) 

This extension will be updated shortly.

**Comment by jumph4x** [comment]
Been solved here for a bit: https://github.com/jumph4x/spree-google-base/commit/3fb63506163c94724fdf42181ec2027523127cd9
