### ISSUE TITLE
wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by samhamilton** [jumph4x/spree-google-base#6]
I get the following error when running locally with Spree 1.1.3, I am not sure what the error means?

Thanks
Sam

% rake spree_google_base:generate_and_transfer --trace
*\* Invoke spree_google_base:generate_and_transfer (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute spree_google_base:generate_and_transfer
rake aborted!
wrong number of arguments (1 for 0)
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:90:in `build_xml'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:50:in`generate_xml'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:37:in `generate_and_transfer_store'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:19:in`block in generate_and_transfer'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:18:in `each'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:18:in`generate_and_transfer'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/tasks/spree_google_base_extension_tasks.rake:5:in `block (2 levels) in <top (required)>'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
/Users/samhamilton/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bin/rake:23:in`load'
/Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bin/rake:23:in `<main>'
Tasks: TOP => spree_google_base:generate_and_transfer

**Comment by jumph4x** [comment]
Will review tomorrow, standby.

**Comment by jumph4x** [comment]
How'd you install the extension? Could you try running this thing through bundler?

```
bundle exec rake spree_google_base:generate_and_transfer --trace
```

**Comment by samhamilton** [comment]
I am testing on a vanilla copy of spree
1. rails new googlebase_testing
2. add gem 'spree' to Gemfile
3. bundle install
4. rails g spree:install (accept all default values)
5. add gem "spree_google_base", :git => 'git://github.com/jumph4x/spree-google-base.git'
6. bundle install
7. rails g spree_google_base:install (accept its request to run migration)
8. rails s
9. http://localhost:3000/admin/google_base_settings/edit
   - add title, domain, description & tick taxon mapping
10. http://localhost:3000/admin/taxon_map
    - add "Apparel & Accessories" to clothing category
11. Error
    % bundle exec rake spree_google_base:generate_and_transfer --trace
    *\* Invoke spree_google_base:generate_and_transfer (first_time)
    *\* Invoke environment (first_time)
    *\* Execute environment
    *\* Execute spree_google_base:generate_and_transfer
    rake aborted!
    wrong number of arguments (1 for 0)
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:90:in `build_xml'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:50:in`generate_xml'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:37:in `generate_and_transfer_store'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:19:in`block in generate_and_transfer'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:18:in `each'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/spree_google_base/feed_builder.rb:18:in`generate_and_transfer'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bundler/gems/spree-google-base-3fb63506163c/lib/tasks/spree_google_base_extension_tasks.rake:5:in `block (2 levels) in <top (required)>'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`block in invoke_with_call_chain'
    /Users/samhamilton/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`block in run'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bin/rake:23:in`load'
    /Users/samhamilton/.rvm/gems/ruby-1.9.3-p194/bin/rake:23:in `<main>'
    Tasks: TOP => spree_google_base:generate_and_transfer

**Comment by jumph4x** [comment]
Thank you, very helpful. 

Will review, fix and follow up soon.

**Comment by jumph4x** [comment]
Been fixed.
